import generateAuthUrl from './generate-auth-url.js';
import verifyCredentials from './verify-credentials.js';
import isStillVerified from './is-still-verified.js';

export default {
  fields: [
    {
      key: 'authMethod',
      label: 'Authentication Method',
      type: 'dropdown',
      required: true,
      value: 'oauth',
      options: [
        { label: 'OAuth (Business App)', value: 'oauth' },
        { label: 'Manual Token Entry', value: 'manual' },
      ],
      description: 'Choose how to authenticate with Facebook',
    },
    {
      key: 'oAuthRedirectUrl',
      label: 'OAuth Redirect URL',
      type: 'string',
      required: false,
      readOnly: true,
      value: '{WEB_APP_URL}/app/facebook/connections/add',
      placeholder: null,
      description: 'OAuth callback URL for Facebook Login',
      clickToCopy: true,
      dependsOn: ['authMethod'],
      showWhen: 'oauth',
    },
    {
      key: 'appId',
      label: 'App ID',
      type: 'string',
      required: true,
      readOnly: false,
      value: null,
      placeholder: null,
      description: 'Your Facebook App ID',
      clickToCopy: false,
      dependsOn: ['authMethod'],
      showWhen: 'oauth',
    },
    {
      key: 'appSecret',
      label: 'App Secret',
      type: 'string',
      required: true,
      readOnly: false,
      value: null,
      placeholder: null,
      description: 'Your Facebook App Secret',
      clickToCopy: false,
      dependsOn: ['authMethod'],
      showWhen: 'oauth',
    },
    {
      key: 'pageAccessToken',
      label: 'Page Access Token',
      type: 'string',
      required: true,
      readOnly: false,
      value: null,
      placeholder: 'EAABwzLixnjYBO...',
      description: 'Facebook Page Access Token (NOT User Token). Get from Graph API Explorer: Select your app → Get Token → Page Access Token → Select your page → Generate Access Token',
      clickToCopy: false,
      dependsOn: ['authMethod'],
      showWhen: 'manual',
    },
    {
      key: 'pageId',
      label: 'Facebook Page ID',
      type: 'string',
      required: true,
      readOnly: false,
      value: null,
      placeholder: '123456789012345',
      description: 'Your Facebook Page ID. Find in Page Settings → Page Info → Page ID, or use Graph API Explorer: GET /{page-name}?fields=id',
      clickToCopy: false,
      dependsOn: ['authMethod'],
      showWhen: 'manual',
    },
    {
      key: 'instagramAccountId',
      label: 'Instagram Account ID',
      type: 'string',
      required: false,
      readOnly: false,
      value: null,
      placeholder: '987654321098765',
      description: 'Instagram Business Account ID (optional)',
      clickToCopy: false,
      dependsOn: ['authMethod'],
      showWhen: 'manual',
    },
  ],

  generateAuthUrl,
  verifyCredentials,
  isStillVerified,
};